#Config Version:
confVersion: 3

# Messages:
msgSearch: "&6Finding location..."
msgLoc: "&aLocation: &c{x} {y} {z}"
msgReload: "&3Reloaded RTP Me!"
msgArgsPerm: "&cInvalid arguments and or permission"
msgCooldown: "&eRTP is on a cooldown please wait &6{timeleft}&e seconds."
msgBlacklistedWorld: "&cYou cannot rtp in this world."

# Max distances
MaxX: 1500
MaxZ: 1500

# Min distances
MinX: 500
MinZ: 500

# Cooldown timer (Seconds):
Cooldown: 120

# Should /rtp teleport you to this world and this world only?
# If set to "false" the user will be randomly placed in the world they are currently in
ForceWorld:
  enabled: false
  world: "world"

# A list of worlds that /rtp will not work in
BlacklistedWorlds:
  - worldname