name: RTP-Me
version: 1.3-SNAPSHOT
main: us.thezircon.play.rtpme.RTPMe
authors: [BUTTERFIELD8, Goldfish]
softdepend: [Vault]
description: Teleports a player to an unknow location
commands:
  rtp:
    description: Teleports player to a random location.
